<a href="https://colab.research.google.com/github/hikmatfarhat-ndu/CSC645/blob/master/keras_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Copyright 2020 Hikmat Farhat

### Callable Objects in Python

In [9]:
class myclass:
  def __init__(self):
    self.x=2
  def __call__(self,y):
    return self.x*y 

In [12]:
c=myclass()
c(4)

8

In [16]:
import tensorflow as tf
from tensorflow import keras

In [27]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_dim, units), dtype="float32"),
            trainable=True,
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(units,), dtype="float32"), trainable=True
        )

    def call(self, inputs):
        print("calling call")
        return tf.matmul(inputs, self.w) + self.b

In [28]:
x = tf.ones((2, 2))
linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)

calling call
tf.Tensor(
[[-0.0381257  -0.07652537  0.00094068  0.05785849]
 [-0.0381257  -0.07652537  0.00094068  0.05785849]], shape=(2, 4), dtype=float32)


In [42]:
input=keras.Input(shape=(2,2))
first=Linear(4,2)(input)
second=Linear(4,4)(first)
model=tf.keras.models.Model(input,second)
x=model(y)
y=tf.ones((2,2))
print(type(second))

calling call
calling call
calling call
calling call
<class 'tensorflow.python.framework.ops.Tensor'>


In [43]:
print(x)
print(input.shape)
print(input.dtype)
print(type(input))

tf.Tensor(
[[-0.00895206 -0.00770739  0.00753834  0.00391943]
 [-0.00895206 -0.00770739  0.00753834  0.00391943]], shape=(2, 4), dtype=float32)
(None, 2, 2)
<dtype: 'float32'>
<class 'tensorflow.python.framework.ops.Tensor'>
